languageCode: "en-us"
baseUrl: "https://blog.aftnet.net"
title: "Aftnet Blog"
theme: "anubis"
paginate: 10
#disqusShortname: "yourdiscussshortname"
googleAnalytics: "G-YXPWFSLCRB"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Alberto Fustinoni"
  email: malberto@aftnet.net # used for microformats
  avatar: "/images/avatar.png" # used for microformats
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  social:
  - id: github
    name: aftnet
  - id: reddit
    name: kaworu1986